#!/usr/bin/env bash

# Build the offset_index container

# Abort on failure:
set -e

# Get current directory, 
# see: https://stackoverflow.com/questions/59895/get-the-source-directory-of-a-bash-script-from-within-the-script-itself
CUR_DIR=`dirname $(readlink -f $0)`

# Copy version file:
cp $CUR_DIR/../VERSION $CUR_DIR/docker/VERSION.tmp

# Build a docker image of offset_index:
docker build $CUR_DIR/docker -t offset_index

# Remove version file:
rm -rf $CUR_DIR/docker/VERSION.tmp
