#!/usr/bin/env bash

# Arguments:
# - index identity file
# - client listening port
# - server listening port
# - Directory of trusted index servers

# Abort on failure:
set -e

# Current directory:
CUR_DIR=`dirname $(readlink -f $0)`

docker run -d \
        --name offst_index \
        -v $1:/ident/index.ident \
        -p $2:5050 \
        -p $3:5051 \
        -v $4:/trusted \
        offst_index



