# Based on 
# https://jjasghar.github.io/blog/2018/11/14/using-travis-ci-deploying-docker-container-to-the-public-docker-registry/

os: linux
dist: bionic
language: minimal

services:
  - docker

# Build docker images:
script:
- index/build
- relay/build
- node/build

deploy:
  provider: script
  script: ci/deploy.sh
  on:
    repo: freedomlayer/offset_docker
    # Deploy when merged to master
    branch: master
