#!/usr/bin/env bash

# Arguments:
# - node identity file
# - node database
# - trusted apps directory
# - Listening port (for apps)

# Abort on failure:
set -e

# Current directory:
CUR_DIR=`dirname $(readlink -f $0)`

docker run -d \
        --name offset_node \
        -v $1:/ident/node.ident \
        -v $2:/db/node.db \
        -v $3:/trusted \
        -p $4:4040 \
        offset_node



