#!/usr/bin/env bash

# Build the offst_relay container

# Abort on failure:
set -e

# Get current directory, 
# see: https://stackoverflow.com/questions/59895/get-the-source-directory-of-a-bash-script-from-within-the-script-itself
CUR_DIR=`dirname $(readlink -f $0)`

# Build a docker image of offst_relay:
docker build $CUR_DIR/docker -t offst_relay
