#!/usr/bin/env bash

# Arguments:
# - Relay identity file
# - Listening port

# Abort on failure:
set -e

# Current directory:
CUR_DIR=`dirname $(readlink -f $0)`

docker run -d \
        --name offst_relay \
        -v $1:/ident/relay.ident \
        -p $2:8080 \
        offst_relay



